---
title: JakeJnx.com
collections:
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:categories/:name"
    label: portfolio
  blog:
    title: Blog
    output: true
    permalink: "/:collection/:categories/:name"
    label: blog
  uploads:
    title: Uploads
    output: true
author:
  name: Jake Jenkins
  email: dev@jakejnx.com
description: JakeJnx is a software development company based in South Wales providing custom app building, website design and support in Cardiff, Newport and Bristol. 
baseurl: 
url: https://jakejnx.com
show_excerpts: false
minima:
  date_format: "%-d %b %Y"
include:
- _headers
theme: minima
plugins:
- jekyll-seo-tag
- jekyll-sitemap