---
title: JakeJnx.com
timezone: UTC
collections:
  blog:
    title: Blog
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: blog
  values:
    layout: post
    permalink: "/blog/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
plugins:
- jekyll-seo-tag
